# Header
menu:
  Home: /
  GitHub: https://github.com/wzqcongcong
  Archives: /archives
  Me: /about

#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- tag
- tagcloud
- recent_posts
- archive
- links

# Links
links:
  Weibo: http://weibo.com/u/1272660443

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id: 