# Header
menu:
  Home: /
  Archives: /archives
  Me: /about/me.html
  She: /about/she.html

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- weibo
- tagcloud
- recent_posts

# Links
links:
  Weibo: http://weibo.com/u/1272660443

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id: 