# Header
menu:
  Home: /
  Archives: /archives
  Me: /about/me.html
  She: /about/she.html

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- weibo
- category
- tagcloud
# - recent_posts
- links

# Links
links:
  Emoji: http://www.emoji-cheat-sheet.com/

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id: 