# Logo
logo: # Empty this to unset logo: css/images/logo.png

# Header
menu:
  Home: /
  Archives: archives
  # Categories: categories
  # Tags: tags
  Me: about/me.html

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # whether to show profile bar
gravatar: false # whether to use gravatar with the email
showlogo: false # whether to show the logo in the header

# Sidebar
sidebar: false # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
# - tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  send: mailto:wzqcongcong@sina.com
  github: http://github.com/wzqcongcong
  twitter: https://twitter.com/wzqcongcong
  # facebook: '#'
  # dribbble: '#'
  rss: atom.xml

# Links
links:
  Hexo: http://hexo.io

# CDN
cdn: #If your site loads slowly change it to "google" , because "useso" is slow out of China. Empty this to use staticfile.

# Miscellaneous
google_site_verification:
google_analytics: UA-58630641-1
favicon: favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
